### ISSUE TITLE
Issue with migrate

### ISSUE THREAD

**Issue by DAlvGar** [rdkit/django-rdkit#18]
Hi all,

I am trying to build a REST API around an existing command line tool I had which is connected to a postgres db using rdkit cartridge. I am trying to use django for building the server around the app and using the existing DB. 

After setting up the project, the app etc. and configuring settings.py to use the existing db, I run an inspectdb with good results.  I copied the output to models.py file with the suggested models. I replaced the generic types suggested by django by the models provided in django-rdkit (I have some Mol and BFP columns). When I finally call the `manage.py migrate`, I get the following error:

what am I doing wrong?? I'd really appreaciate your help! 

`Running migrations:
  Applying chemspace_server.0001_initial... OK
  Applying django_rdkit.0001_setup...Traceback (most recent call last):
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedObject: type "mol" does not exist
LINE 1: SELECT mol_to_smiles('C'::mol)
                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django_rdkit/operations.py", line 16, in database_forwards
    c.execute("SELECT mol_to_smiles('C'::mol)")
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dalvarez/miniconda3/envs/chemspace/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: type "mol" does not exist
LINE 1: SELECT mol_to_smiles('C'::mol)`

**Comment by DAlvGar** [comment]
OK I found myself the answer. I was using a schema "schemename" within the database so in my settings I had this:
```

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=schemename'
        },
        'NAME': 'name',
        'USER': 'user',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
```
Then rdkit functions where not available. Finally I found out that if I was not declaring the schemename, the functions were there. 
So I modified the search_path to include the public scheme as well and everything seems to work now:

```

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=schemename,public'
        },
        'NAME': 'name',
        'USER': 'user',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
```

**Comment by rvianello** [comment]
@DAlvGar sorry about the slow reply, I am glad you solved the problem (the root cause would have been difficult to me to identify and I would have started with some very generic questions about the setup), and thanks a lot for sharing the solution, it's an interesting use case.
